FROM jenkins/jenkins:lts-jdk21
USER root
COPY jenkins_backup.tar.gz /jenkins_backup.tar.gz
RUN mkdir -p /var/jenkins_home && \
    tar xzf /jenkins_backup.tar.gz -C /var/jenkins_home && \
    rm /jenkins_backup.tar.gz && \
    echo 2.0 > /var/jenkins_home/jenkins.install.InstallUtil.lastExecVersion && \
    echo 2.0 > /var/jenkins_home/jenkins.install.UpgradeWizard.state
USER jenkins